services:
  search_game_handler:
    container_name: s_g_h
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python app/main.py
    depends_on:
      - db
#      - redis
#      - kafka
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REQUEST_TOPIC: user-events
      ANSWER_TOPIC: response_handler_events
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: search-game
    networks:
      - shared_network

#  redis:
#    image: redis:latest
#    container_name: redis_2
#    restart: always
#    ports:
#      - "6379:6379"
#    networks:
#      - shared_network
#
#  kafka:
#    image: bitnami/kafka:2.8.0
#    container_name: kafka_2
#    restart: always
#    depends_on:
#      - zookeeper
#    ports:
#      - 9092:9092
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      ALLOW_PLAINTEXT_LISTENER: yes
#    networks:
#      - shared_network
#    volumes:
#      - kafka_data:/var/lib/kafka/data
#
#  zookeeper:
#    image: bitnami/zookeeper:3.7.0
#    container_name: zookeeper_2
#    restart: always
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ALLOW_ANONYMOUS_LOGIN: yes
#    ports:
#      - '2181:2181'
#    networks:
#      - shared_network
#
#  kafdrop:
#    image: obsidiandynamics/kafdrop
#    container_name: kafdrop_2
#    restart: always
#    ports:
#      - "9000:9000"
#    environment:
#      KAFKA_BROKERCONNECT: kafka:9092
#      JVM_OPTS: "-Xms32M -Xmx64M"
#      SERVER_SERVLET_CONTEXTPATH: "/"
#    depends_on:
#      - kafka
#    networks:
#      - shared_network

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=search-game
    ports:
      - 5432
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  postgres_data:
#  kafka_data: