services:
  search_game_handler:
    container_name: s_g_h
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python app/main.py
    depends_on:
      - db
#      - redis
#      - kafka
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REQUEST_TOPIC: user-events
      ANSWER_TOPIC: response_handler_events
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: search-game
    networks:
      - shared_network

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=search-game
    ports:
      - 5432
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  postgres_data:
#  kafka_data: